# Generated by Django 3.0.3 on 2020-02-17 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 2, 17, 17, 28, 43, 81957)),
        ),
    ]
