# Generated by Django 3.0.3 on 2020-03-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegularStudy',
            new_name='Regular',
        ),
        migrations.RenameModel(
            old_name='TemporaryStudy',
            new_name='Temporary',
        ),
    ]
