# Generated by Django 3.0.3 on 2020-03-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
