# Generated by Django 3.0.5 on 2020-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200403_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='quit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
