# Generated by Django 3.0.3 on 2020-02-17 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_study_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='study',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 2, 17, 18, 11, 39, 809990)),
        ),
    ]
