# Generated by Django 3.0.3 on 2020-03-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200305_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporary',
            name='did',
        ),
    ]
