# Generated by Django 3.0.5 on 2020-04-03 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_consulting'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='content',
            field=models.TextField(default='f'),
        ),
        migrations.AddField(
            model_name='consulting',
            name='when_consult',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
