# Generated by Django 3.0.5 on 2020-04-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200403_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='content',
            field=models.TextField(),
        ),
    ]
