# Generated by Django 3.0.5 on 2020-04-06 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200403_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
