# Generated by Django 3.0.3 on 2020-02-18 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200217_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='days_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='study',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 2, 18, 16, 35, 50, 586770)),
        ),
    ]
