# Generated by Django 3.0.3 on 2020-02-18 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200218_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['class_name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['group']},
        ),
        migrations.AlterField(
            model_name='study',
            name='time',
            field=models.TimeField(choices=[(datetime.time(16, 0), '16:00'), (datetime.time(16, 20), '16:20'), (datetime.time(16, 40), '16:40'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 20), '17:20'), (datetime.time(17, 40), '17:40'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 20), '18:20'), (datetime.time(18, 45), '18:45'), (datetime.time(19, 5), '19:05'), (datetime.time(19, 25), '19:25'), (datetime.time(20, 10), '20:10'), (datetime.time(20, 30), '20:30'), (datetime.time(20, 50), '20:50'), (datetime.time(21, 15), '21:15'), (datetime.time(21, 35), '21:35'), (datetime.time(21, 55), '21:55'), (datetime.time(22, 20), '22:20'), (datetime.time(22, 40), '22:40'), (datetime.time(23, 0), '23:00'), (datetime.time(23, 20), '23:20')]),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('korean_name', 'eng_name')},
        ),
    ]
