# Generated by Django 3.0.5 on 2020-04-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200407_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulting',
            options={'ordering': ['when_consult', 'student']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name', 'grade']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['status', 'cur_class', 'kor_name']},
        ),
    ]
