# Generated by Django 3.0.3 on 2020-02-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200218_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['time', 'days_of_week', 'teacher']},
        ),
        migrations.AlterField(
            model_name='study',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_type',
            field=models.ForeignKey(default='Regular', on_delete=django.db.models.deletion.CASCADE, to='students.StudyType'),
        ),
        migrations.AlterUniqueTogether(
            name='study',
            unique_together={('teacher', 'days_of_week', 'time')},
        ),
    ]
