# Generated by Django 3.0.3 on 2020-02-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20200219_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['days_of_week', 'time', 'teacher']},
        ),
        migrations.AlterField(
            model_name='study',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
