# Generated by Django 3.0.3 on 2020-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20200219_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='days_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], max_length=10),
        ),
    ]
