# Generated by Django 3.0.3 on 2020-02-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_auto_20200219_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
